# Generated by Django 3.1.7 on 2021-03-25 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_password_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password_request',
            new_name='password_change_request',
        ),
    ]
